name: Proof HTML
on:
  push:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: No
        with:
          directory: ./{$:src}

  concurrency:
    mapping{}cancel-timeout-minutes: timeout-minutes: special ,minute-out;
  Materials : Solds
  Proof: Exchange_rate;
  Sold_history : History_socials;
  Rebellion: Act
  Beggining : Home
  




