name: Proof HTML
on:
  push:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: anishathalye/proof-html@v1.1.0
        with:
          directory: ./

Dispatch: Proof: {

         ordered, numerous: calculations: [Fact-code] , l b m}



  Retina: seoul ? 
  Patch: act-inno?


  



}Dance@10



